### ISSUE TITLE
friends_dates.rb:34:in `parse': invalid date (ArgumentError)

### ISSUE THREAD

**Issue by magnusoverli** [Lackoftactics/facebook_data_analyzer#18]
Running the script on macOS 10.13.4.
This is the only output:
...
Analyzing conversation with: 
Analyzing conversation with: 
Analyzing conversation with: 
Analyzing conversation with: 
Analyzing conversation with: 
Traceback (most recent call last):
	9: from analyze_facebook_data.rb:52:in `<main>'
	8: from analyze_facebook_data.rb:52:in `new'
	7: from /Users/magnus/facebook_data_analyzer/lib/workbook.rb:8:in `initialize'
	6: from /Users/magnus/facebook_data_analyzer/lib/friends_dates.rb:11:in `analyze'
	5: from /Users/magnus/facebook_data_analyzer/lib/friends_dates.rb:20:in `analyze'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `each'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `upto'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:190:in `block in each'
	1: from /Users/magnus/facebook_data_analyzer/lib/friends_dates.rb:34:in `block in analyze'
/Users/magnus/facebook_data_analyzer/lib/friends_dates.rb:34:in `parse': invalid date (ArgumentError)

**Comment by MetricMike** [comment]
This is most often due to date localization. Did you download the archive with your language set to English US?

Can you provide a snippet of a message that contains the date so we can try to reproduce?

(We should definitely make this easier for users)

**Comment by magnusoverli** [comment]
No, the language was set to my local language. Unfortunately, the account is now deleted, so I cannot recreate the data. Would it be possible to update the script with support for other locales?

**Comment by Lackoftactics** [comment]
@magnusoverli it's tricky with other languages, we don't plan it for now.
