### ISSUE TITLE
Add circleCI as checks

### ISSUE THREAD

**Issue by thnukid** [Lackoftactics/facebook_data_analyzer#36]
@Lackoftactics 
In a PR there is a tab with "Checks", could you add circleci to this repository, so that the project benefits from the ci, that was added #31 ?

<img width="1905" alt="screen shot 2018-06-13 at 09 25 37" src="https://user-images.githubusercontent.com/1724804/41336202-cfd8eeba-6eeb-11e8-88ed-e2ba4d864d08.png">

Then we can also add a badge to the readme:
https://circleci.com/docs/1.0/status-badges/

**Comment by Lackoftactics** [comment]
@thnukid thanks for pointing that out. @marzann great work, sorry for not adding this sooner

**Comment by thnukid** [comment]
I do not see the checks activated in the github repository.

**Comment by marzann** [comment]
@thnukid: Last two commits: 71f9d00 and 0099968, have checks. 
@Lackoftactics: no worries, glad to be able to contribute. 
More info on checks here: https://help.github.com/articles/enabling-required-status-checks/
My checks go back to May 8, and they were configured automatically.
