### ISSUE TITLE
Try parallel gem for faster processing of data

### ISSUE THREAD

**Issue by Lackoftactics** [Lackoftactics/facebook_data_analyzer#7]
@Skeyelab Proposed using https://github.com/grosser/parallel for parallel processing. To be honest I don't have experience with that. Any thoughts, guys? @pawelgut @jamjar919

**Comment by MetricMike** [comment]
I've been playing around with this today and the major bottleneck is the `AnalyzeMessages` block (averaging ~1-2 minutes on my facebook data with ruby-prof wrapping it). Most other top-level blocks complete in <1 second.

`AnalyzeMessages` is i/o bound, so threads are no good, but using processes for each of my cores:
```ruby
messages_files.each do |file|
```
with:
```ruby
Parallel.each(messages_files, in_processes: 4) do |file|
```
that block dropped to ~15-20 seconds (a  3-6x speedup).

I'm waiting for #8 to merge before I make a PR on top of it

**Comment by krishna015** [comment]
I tried running the script. First, I use a windows machine, got no file or directory error As .htm is mentioned instead of .html in line 52.  Tried updating it to .html and got one more error - No such file or directory error (line - 236) (I don't have the directory (html) in my facebook downloaded data).

Can anyone please help? Thanks !

**Comment by MetricMike** [comment]
@krishna015 that sounds like a bad archive from facebook. After unzipping you should have a directory that looks like:
![image](https://user-images.githubusercontent.com/311365/38770383-56997dba-3fe0-11e8-805d-bdb6720c0dbc.png)

and the HTML directory looks like:
![image](https://user-images.githubusercontent.com/311365/38770400-9d3796a8-3fe0-11e8-9a14-b3c27b4bd9c8.png)

Try redownloading your archive

**Comment by MetricMike** [comment]
Pausing work on this in favor of #10 - when helping out with #8 I discovered that Parallel often resulted in an empty .xlsx, so I'm betting we're not thread-safe somewhere.

Having a test suite and an example archive will go a long way to solving this issue!

**Comment by northcott-j** [comment]
@MetricMike I was able to get a speed increase while using Parallel when I processed each file using `Parallel.each(messages_files, in_processes: 4) do |file|`, saving the various hashes and arrays (e.g. `@friends`, `@my_messages_dates` etc.) to a temporary `_#{file}.json`.

I then used Parallel again, but with threads and a semaphore, to open each `json` and aggregate the info. I found that I couldn't share memory and vars across processes, so I used a physical file as a temp store. 

With the size of my dataset, the second Parallel to process each `json` wasn't much faster than aggregating each file one at a time, but it may vary from catalog to catalog.

**Comment by Lackoftactics** [comment]
@northcott-j I need to review that and will comeback to you but looks really interesting. So the speed increase is from json or parallel? Maybe we don't need any parallel gems, probably there won't be speed increase on other catalogs if it doesn't work with yours, I will check on mine. 

We are also on subject of dummy data, so in the future we could create some large file with dummy example data and run against it, to test if it really makes difference with parallel processing.

**Comment by northcott-j** [comment]
@Lackoftactics the Parallel gem makes a pretty large difference with my catalog. About a 2x speed-up. For repeated runs where I don't change any message information but edited some other areas of the code, the way I have it implemented gives me roughly a 20x speed increase.

The part that I'm not sure if concurrency is necessary or not is when I join the JSON files. I didn't notice a speed boost in that case for my catalog. 

In the PR I opened (#13), the current flow is:
1. Use multiple processes to process a message.html file and save it as a JSON
2. Use multiple threads to join each individual JSON 
3. Continue on with the process as normal

It's in step 2 where I don't notice a difference if I do it concurrently, but step 1 definitely speeds up the time it takes to process my catalog.

**Comment by Lackoftactics** [comment]
@northcott-j  thank you for you answer. If that's the case we should definitely go with this
